openapi: '3.0.2'
info:
  title: API для лабораторных по микропроектированию
  version: '1.0'

tags:
  - name: Authentication
    description: Аутентификация
  - name: PasswordRecovering
    description: Восстановление пароля

paths:
  /log-in:
    $ref: "paths/log_in.yml"
  /log-out:
    $ref: "paths/log_out.yml"
  /send-recovery-letter:
    $ref: "paths/send_recovery_letter.yml"
  /check-recovery-token:
    $ref: "paths/check_recovery_token.yml"
  /change-password:
    $ref: "paths/change_password.yml"

components:
  securitySchemes:
    $ref: "security/jwt.yml"
